# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.11
_src_path: gh:algorandfoundation/algokit-python-template
author_email: kitan@goodthingco.xyz
author_name: Kitan
contract_name: cert
deployment_language: python
preset_name: production
project_name: vericert

